### ISSUE TITLE
get upcoming events for 30 days

### ISSUE THREAD

**Issue by Eddie425** [morugu/timetree-sdk-python#3]
Hi just wondering is that possible to get upcoming events for 30 days?

**Comment by morugu** [comment]
@Eddie425  yes. please try following code.

```python
events = api.get_upcoming_events('CALENDAR_ID', 'Asia/Tokyo', 30)
```

**Comment by Eddie425** [comment]
Thanks, I will try this.

**Comment by morugu** [comment]
@Eddie425  Sorry, I misunderstood. upcoming events days range is 1 - 7. 
Unfortunately it is difficult.

**Comment by Eddie425** [comment]
Got it, I will find the other way...Thanks a lot😁
